# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientMainWindow(object):
    def setupUi(self, ClientMainWindow):
        ClientMainWindow.setObjectName("ClientMainWindow")
        ClientMainWindow.resize(1280, 800)
        ClientMainWindow.setMinimumSize(QtCore.QSize(1280, 800))
        ClientMainWindow.setMaximumSize(QtCore.QSize(1280, 800))
        self.centralwidget = QtWidgets.QWidget(ClientMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ipInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ipInput.setObjectName("ipInput")
        self.horizontalLayout.addWidget(self.ipInput)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.portInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.portInput.setObjectName("portInput")
        self.horizontalLayout.addWidget(self.portInput)
        self.Connect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Connect.setObjectName("Connect")
        self.horizontalLayout.addWidget(self.Connect)
        self.disConnect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.disConnect.setObjectName("disConnect")
        self.horizontalLayout.addWidget(self.disConnect)
        self.fileManager = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.fileManager.setObjectName("fileManager")
        self.horizontalLayout.addWidget(self.fileManager)
        self.regManager = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.regManager.setObjectName("regManager")
        self.horizontalLayout.addWidget(self.regManager)
        self.openCamera = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.openCamera.setObjectName("openCamera")
        self.horizontalLayout.addWidget(self.openCamera)
        self.openMicrophone = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.openMicrophone.setObjectName("openMicrophone")
        self.horizontalLayout.addWidget(self.openMicrophone)
        self.keylogger = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.keylogger.setObjectName("keylogger")
        self.horizontalLayout.addWidget(self.keylogger)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        ClientMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ClientMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ClientMainWindow)

    def retranslateUi(self, ClientMainWindow):
        _translate = QtCore.QCoreApplication.translate
        ClientMainWindow.setWindowTitle(_translate("ClientMainWindow", "客户端（控制端）"))
        self.label.setText(_translate("ClientMainWindow", "服务端地址"))
        self.ipInput.setText(_translate("ClientMainWindow", "localhost"))
        self.label_2.setText(_translate("ClientMainWindow", "服务端端口"))
        self.Connect.setText(_translate("ClientMainWindow", "连接"))
        self.disConnect.setText(_translate("ClientMainWindow", "断开连接"))
        self.portInput.setText(_translate("ClientMainWindow", "25566"))
        self.fileManager.setText(_translate("ClientMainWindow", "文件管理"))
        self.regManager.setText(_translate("ClientMainWindow", "注册表管理"))
        self.openCamera.setText(_translate("ClientMainWindow", "开启摄像头"))
        self.openMicrophone.setText(_translate("ClientMainWindow", "开启麦克风"))
        self.keylogger.setText(_translate("ClientMainWindow", "键盘记录"))
